version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DATABASE_URL=sqlite+aiosqlite:///./app.db
    volumes:
      - ./app:/app/app
      - app_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      target: production
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api
    restart: unless-stopped
    command: ["python", "-m", "streamlit", "run", "frontend/main.py", "--server.port", "8501", "--server.address", "0.0.0.0"]

volumes:
  app_data:
